name: Deploy to GKE

on:
  push:
    branches:
      - master
      - devel
  pull_request:
    branches:
      - master
      

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: fib-cluster-1
  GKE_ZONE: europe-west2-c 
  DEPLOYMENT_NAME: gke-hello-app # TODO: update deployment name if changed in deployment.yaml
  # SHA: $(git rev-parse HEAD)
  # GITHUB_SHA

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - run: docker login -u ${{ secrets.DOCKER_ID }} -p '${{ secrets.DOCKER_PASSWORD }}'
    - run: docker build -t holadepo/react-test -f ./client/Dockerfile.dev ./client
    - run: docker run -e CI=true holadepo/react-test npm run test

    - run: docker build -t holadepo/fib-client:latest -t holadepo/fib-client:$GITHUB_SHA ./client
    - run: docker build -t holadepo/fib-server:latest -t holadepo/fib-server:$GITHUB_SHA ./server
    - run: docker build -t holadepo/fib-worker:latest -t holadepo/fib-worker:$GITHUB_SHA ./worker


  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/master'

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Alternative option - authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - run: docker login -u ${{ secrets.DOCKER_ID }} -p '${{ secrets.DOCKER_PASSWORD }}'

    - run: docker build -t holadepo/fib-client:latest -t holadepo/fib-client:$GITHUB_SHA ./client
    - run: docker build -t holadepo/fib-server:latest -t holadepo/fib-server:$GITHUB_SHA ./server
    - run: docker build -t holadepo/fib-worker:latest -t holadepo/fib-worker:$GITHUB_SHA ./worker

    - run: docker push holadepo/fib-client:latest
    - run: docker push holadepo/fib-server:latest
    - run: docker push holadepo/fib-worker:latest

    - run: docker push holadepo/fib-client:$GITHUB_SHA
    - run: docker push holadepo/fib-server:$GITHUB_SHA
    - run: docker push holadepo/fib-worker:$GITHUB_SHA

    # Deploy sample image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl apply -f k8s
        kubectl set image deployments/server-deployment server=holadepo/fib-server:$GITHUB_SHA
        kubectl set image deployments/client-deployment client=holadepo/fib-client:$GITHUB_SHA
        kubectl set image deployments/worker-deployment worker=holadepo/fib-worker:$GITHUB_SHA
        kubectl get services -o wide
